Config: Criar Entidades
Javeiros-brasil/helpmatch-backend pull request #14
Opened 2023-05-31 02:05 UTC by arthur-j1

2023-05-31 02:35 UTC, iurysalino requested changes
Alterações solicitadas.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Agendamento.java
> +    private int clienteId;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Agendamento.java
> +    private int servicoId;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Cliente.java
> +    private Long contatosId;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Cliente.java
> +    private Long enderecosId;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Cliente.java
> +    private Long acessoId;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Servico.java
> +    private long profissionalId;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Cliente.java
> +    private List<Agendamento> agendamentos;
Esse campo se relaciona com outra entidade, favor adicionar a anotação do relacionamento.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Servico.java
> +public class Servico {
A classe está pendente de anotações de Entidade, getter e setter, no e all args constructor.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Acesso.java
> +@Getter
Utilize o `@Data`, pois ele já contém o `@Getter` e `@Setter` embutidos.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Agendamento.java
> +@Getter
Utilize o `@Data`, pois ele já contém o `@Getter` e `@Setter` embutidos.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Cliente.java
> +@Getter
Utilize o `@Data`, pois ele já contém o `@Getter` e `@Setter` embutidos.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Contato.java
> +@Getter
Utilize o `@Data`, pois ele já contém o `@Getter` e `@Setter` embutidos.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Endereco.java
> +@Getter
Utilize o `@Data`, pois ele já contém o `@Getter` e `@Setter` embutidos.

2023-05-31 02:35 UTC, iurysalino commented on src/main/java/br/com/helpmatch/entitys/Servico.java
> +public class Servico {
Utilize o `@Data`, pois ele já contém o `@Getter` e `@Setter` embutidos.

2023-06-22 20:03 UTC, gilberto-009199 commented
:1st_place_medal: Muito bem, finalizado a minha analise e correção.
Falta o parecer do @iurysalino agora!

2023-06-22 20:13 UTC, iurysalino commented
Alterações aprovadas, solicitando o MPR

2023-06-22 20:13 UTC, merged